### PR TITLE
Autolayout fixes

### PR DESCRIPTION
**Pull request by pmkowal**
Hi @bonzoq, I updated constraints in couple of views to get rid of warnings from the storyabord. I also fixed displaying of time when the `urlDomain` is empty. Can you take a look please?

### CODE REVIEW

**Comment by bonzoq** [comment]
Hi Pawel,

thanks for contributing! This looks very promising. I will give it a look and if the code review and regression tests go well I will merge your PR hopefully later today.

**Comment by pmkowal** [comment]
Thanks @bonzoq!

**Comment by pmkowal** [comment]
@bonzoq, plase check again, thx

**Comment by bonzoq** [comment]
Your auto-layout works like a charm. Thanks for contributing!

**Comment by pmkowal** [comment]
Thank you! 🎉

**Pull request merged**
