### PR TITLE
Add ability to view story from comments.

### PR DESCRIPTION
**Pull request by michelmansour**
- Make the story title tap-able from comments view.
- Add a protocol to comment view controller so that the story index is aware
of when a story is read from the comments and can react accordingly.

### CODE REVIEW

**Comment by michelmansour** [comment]
Thanks for making this app and distributing it for free -- and making it open source! It's a delight to use. One feature I've been missing is being able to open a story from the comments, so I figured I'd try to contribute. If it was a design decision on your part to leave out that functionality, then no worries. Otherwise, feel free to do what you want with this PR, and let me know if there are any changes you'd like me to make. Cheers!

**Comment by bonzoq** [comment]
Hi Michel,

thanks for contributing! 

Tapping the story from the comments view was disabled on purpose. I thought that users might miss the back button and get annoyed by being taken to the webview instead.

However, your code seems to be of excellent quality and it would be a shame not to use it. I will therefore increase the tappable are of the back button to make sure no one misses it. 

I will thoroughly test your code and if all goes well I will merge it into the master branch. I hope to get it done by the end of the week, Sunday being most likely. 

Greetings
Marcin

**Comment by michelmansour** [comment]
Hi Marcin,

Thanks for taking a look and considering adding this feature! 

That's a great point regarding usability of the back button. I don't think it's a huge issue since there is already a similar situation on the list of stories view with tapping the read status and comments buttons, which present fairly small tap targets. Expanding the back button's tappable area will certainly help, though.

If there are any style or other such issues you'd like me to clean up before merging, I'll be happy to do so. And of course if you find any bugs during your testing, I can take care of those.

Michel

**Comment by bonzoq** [comment]
Hi Michel,

I went through your code and have to admit it is very clear and a delight to analyse.

What I've noticed is that the text view in comment cells captures taps, and basically the only way to open a story is to tap outside the text view, which is not that obvious and hence could be confusing. 

I see two possible solutions here. Either adding a button to each comment which would take you to the story or enabling selecting the only cell in Section 0 only. Let me know what you think.

Greetings
Marcin

**Comment by michelmansour** [comment]
Hey Marcin,

Good catch! That looks like an unintended behavior (ie, a bug). Tapping anywhere in a comment cell should not have any effect, unless it's a URL of course. Only clicking the title cell in Section 0 should open the web view. Of your two suggestions, I think enabling selection of only the cell in Section 0 is the most appropriate. Let me take a crack at it, and I should be able to update the PR by the end of the week

**Comment by michelmansour** [comment]
Actually, it was a rather quick fix, so I went ahead and did it now :)  I set the comment cells' `selectionStyle` to `UITableViewCellSelectionStyleNone`, and I added a check to `tableView:didSelectRowAtIndexPath` to only show the web view if it's the first row of the first section. The method will still be called when comment cells are tapped, but it will no longer have an effect. URLs in comments are still selectable. Is this close to what you had in mind?

I also fixed a bug where reading a story from a nested comment view was not properly setting the read status. I had simplly failed to pass along the delegate to the next comment view, so that was a fairly quick fix as well.

Let me know what you think.

**Comment by bonzoq** [comment]
Hey Michel,

thanks for the fixes. I'm merging your pull request now.

I appreciate your contribution very much!

Greetings
Marcin

**Comment by michelmansour** [comment]
Hey Marcin,

Great! More than happy to help. Thanks for accepting and being so responsive! And again, thanks for such a nice app.

Michel

**Pull request merged**
