### PR TITLE
Fix title label line breaks

### PR DESCRIPTION
**Pull request by pmkowal**
Hi @bonzoq, this Pull Request fixes the problem with the line breaks for the `titleLabel`.
Basically the solution is to modify the `trailing spacing` constraint relation for the `titleLabel` from `Equal` to `Greater Than or Equal`.

### CODE REVIEW

**Comment by bonzoq** [comment]
Hello @pmkowal. Thank you for contributing! I will thoroughly test your changes on a device, perform regression as well as unit and functions tests and if everything goes smoothly, your PR will be merged in a few days.

**Comment by pmkowal** [comment]
Ok, great, thank you @bonzoq!

**Comment by pmkowal** [comment]
Thanks for merge @bonzoq!

**Comment by bonzoq** [comment]
Thanks for contributing @pmkowal! If you ever feel the lust to contribute even more you can always have a look at issues as there are always some goodies:).

**Comment by pmkowal** [comment]
:+1:

**Pull request merged**
